### ISSUE TITLE
HtKeepAliveResponse.java:58-66: Replace the HtWire by...

### ISSUE THREAD

**Issue by 0pdd** [yegor256/cactoos-http#74]
The puzzle `20-eb4af059` from #20 has to be resolved: 

https://github.com/yegor256/cactoos-http/blob/1248e0c31b30fbfca43db9ff25ea49b56a527d03/src/main/java/org/cactoos/http/HtKeepAliveResponse.java#L58-L66

The puzzle was created by @rultor on 07-Feb-19. 

  

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by 0crat** [comment]
Job [#74](https://github.com/yegor256/cactoos-http/issues/74) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
The job [#74](https://github.com/yegor256/cactoos-http/issues/74) assigned to @umbrah[/z](https://www.0crat.com/u/umbrah), here is [why](https://www.0crat.com/footprint/C63314D6Z/98df7fc2-3652-4d5a-9be9-2ad5183a3b2f); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by Umbrah** [comment]
@0crat refuse

**Comment by 0crat** [comment]
> @0crat refuse ([here](https://github.com/yegor256/cactoos-http/issues/74#issuecomment-486172118))

@Umbrah The user @umbrah[/z](https://www.0crat.com/u/umbrah) resigned from [#74](https://github.com/yegor256/cactoos-http/issues/74), please stop working. Reason for job resignation: Order was cancelled

**Comment by 0crat** [comment]
Tasks refusal is discouraged, see [§6](http://www.zerocracy.com/policy.html#6): -15 point(s) just awarded to @umbrah[/z](https://www.0crat.com/u/umbrah)

**Comment by 0crat** [comment]
The job [#74](https://github.com/yegor256/cactoos-http/issues/74) assigned to @vzurauskas[/z](https://www.0crat.com/u/vzurauskas), here is [why](https://www.0crat.com/footprint/C63314D6Z/5af8d82b-042d-4d57-a221-a82857226248); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by vzurauskas** [comment]
@0crat wait for https://github.com/yegor256/cactoos-http/issues/84

**Comment by 0crat** [comment]
> @0crat wait for https://github.com/yegor256/cactoos-http/issues/84 ([here](https://github.com/yegor256/cactoos-http/issues/74#issuecomment-488331936))

@vzurauskas The impediment for [#74](https://github.com/yegor256/cactoos-http/issues/74) was registered successfully by @vzurauskas[/z](https://www.0crat.com/u/vzurauskas)

**Comment by vzurauskas** [comment]
@llorllale To understand this better, I created https://github.com/yegor256/cactoos-http/issues/84 But in addition to the more generic questions there, I have a few more related specifically to this task. 

If user wants to perform a series of request-response exchanges with server while keeping connection alive, he would use a pattern similar to the example in [this comment](https://github.com/yegor256/cactoos-http/pull/57#issuecomment-402199387), where each request could reuse the same `HtKeepAliveWire`. But in addition to that, is it the case that his first request should be in a `HtKeepAliveResponse` to tell the server to keep connection alive (it's not the `Wire` that is supposed to do that), and the last request should be a `HtAutoClosedResponse` to close the `Wire`? So something like this?

```java
try (final Wire wire = new HtKeepAliveWire("host")) {
    final Text resp1 = new TextOf(
        new HtKeepAliveResponse(    // Tell the server to keep connection alive.
            wire, "request1"
        )
    );
    final Text resp2 = new TextOf(
        new HtAutoClosedResponse(    // Close the connection when byte stream ends.
            wire, "request2"
        )
    );
}
```

Also, since only the server can specify the `timeout` and `rmax` parameters, and `HtKeepAliveWire` is created by the user directly (not by the `HtResponse`) to be reused by the subsequent requests, the `@todo` description for this task is outdated? Specifically, `HtKeepAliveWire` should not take these parameters in constructor?

**Comment by vzurauskas** [comment]
@llorllale ping

**Comment by vzurauskas** [comment]
@llorllale ping pong

**Comment by llorllale** [comment]
@vzurauskas sorry for the delay

Let's recap:

The `Keep-Alive` header is a hint that can be sent by *either* the client or the server.

`HtKeepAliveResponse` automatically injects the header into the user's HTTP request (decorates the request). We could perhaps rename it to avoid confusion.

`HtKeepAliveWire` is unnecessary - it's just a dumb pipe that either endpoint may decide to close off at any time.

`HtAutoClosedResponse` automatically closes the connection. Useful for one-offs, eg.:

```java
// I don't want to reuse the wire
final String resp = new TextOf(
    new HtAutoClosedResponse(
        new HtResponse("http://servers-r-us.com")
    )
).asString();
```

If you'd like multiple exchanges with the server on the same connection, you do:

```java
try (final Wire wire = new HtWire("host")) {
    final Text resp1 = new TextOf(
        new HtResponse(
            wire,
            "request1"
        )
    );
    final Text resp2 = new TextOf(
        new HtResponse(
            wire,
            "request2"
        )
    );
}
```

**Comment by llorllale** [comment]
@vzurauskas there is one thing I think that's missing from the above - the snippet assumes the server responded with `Keep-Alive` when in fact it may not. The example above would fail after the first request if the server decided to close the connection at the end of that exchange. You can inspect the headers of `HtResponse` with `HtHeaders`.

**Comment by llorllale** [comment]
@vzurauskas finally:

>  the `@todo` description for this task is outdated? 

Yes. We don't need `HtKeepAliveWire` at all.

**Comment by vzurauskas** [comment]
@llorllale Sorry for the delay, this time from me. :)

So if the client wanted to send two requests reusing the connection, the first request should include the `Connection: Keep-Alive` header, right? Therefore the code would look like this (N.B. the first request/response is `HtKeepAliveResponse` with timeout and rmax parameters) ?
```java
try (final Wire wire = new HtWire("host")) {
    final String resp1 = new TextOf(
        new HtKeepAliveResponse(
            wire,
            5, // timeout
            2, // rmax
            "request1"
        )
    ).asString();
    final String resp2 = new TextOf(
        new HtResponse(
            wire,
            "request2"
        )
    ).asString();
}
```

If that's correct, and since this task already took a lot of time and the original description is very outdated now, perhaps I should rewrite the `todo` according to our current understanding of what needs to be done, and we could close this task?

**Comment by vzurauskas** [comment]
@llorllale ping :)

**Comment by 0crat** [comment]
The job [#74](https://github.com/yegor256/cactoos-http/issues/74) assigned to @iakunin[/z](https://www.0crat.com/u/iakunin), here is [why](https://www.0crat.com/footprint/C63314D6Z/c5232e96-d113-42a2-8592-5e966164ef49); the budget is 30 minutes, see [§4](http://www.zerocracy.com/policy.html#4); please, read [§8](http://www.zerocracy.com/policy.html#8) and [§9](http://www.zerocracy.com/policy.html#9); if the task is not clear, read [this](http://www.yegor256.com/2015/02/16/it-is-not-a-school.html) and [this](http://www.yegor256.com/2015/01/15/how-to-cut-corners.html); there will be no monetary reward for this job

**Comment by iakunin** [comment]
@paulodamaso, this is a pretty obscure task. Could you get me the right direction here?

**Comment by paulodamaso** [comment]
@iakunin This issue is focused in implementing keep-alive connections by `cactoos-http` client. Keep-alive connectios trade the `keep-alive` header, so the server and the client would know the type of the http connection being used. Take a look at https://github.com/yegor256/cactoos-http/issues/74#issuecomment-515688229, it explains what shoud be implemented.

**Comment by iakunin** [comment]
@0crat waiting for review https://github.com/yegor256/cactoos-http/pull/95

**Comment by 0crat** [comment]
> @0crat waiting for review https://github.com/yegor256/cactoos-http/pull/95 ([here](https://github.com/yegor256/cactoos-http/issues/74#issuecomment-532337854))

@iakunin The impediment for [#74](https://github.com/yegor256/cactoos-http/issues/74) was registered successfully by @iakunin[/z](https://www.0crat.com/u/iakunin)

**Comment by 0pdd** [comment]
The puzzle `20-eb4af059` has disappeared from the source code, that's why I closed this issue.

**Comment by 0crat** [comment]
The job [#74](https://github.com/yegor256/cactoos-http/issues/74) is now out of scope

**Comment by 0crat** [comment]
Order was finished: +30 point(s) just awarded to @iakunin[/z](https://www.0crat.com/u/iakunin)
